services:
  kuma-control-plane:
    image: kuma/kuma-cp:latest
    environment:
      KUMA_MODE: standalone
    ports:
      - "5681:5681" # Admin REST API
      - "8080:8080" # Kuma GUI
      - "5678:5678" # Dataplane communication
    networks:
      - service_mesh

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000" # Proxy
      - "8001:8001" # Admin API
    networks:
      - service_mesh

networks:
  service_mesh:
    driver: bridge