services:
  apps:
    container_name: example-apps
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    env_file: .env
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    depends_on:
      - control-plane
    networks:
      - service-mesh
    privileged: true

  deployment-platform:
    container_name: deployment-platform
    build:
      context: ..
      dockerfile: ./modules/dokku/Dockerfile
    ports:
      - "3022:22"
      - "80:80"
      - "8443:443"
    volumes:
      - "/var/lib/dokku:/mnt/dokku"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      DOKKU_HOSTNAME: dokku.me
      DOKKU_HOST_ROOT: /var/lib/dokku/home/dokku
      DOKKU_LIB_HOST_ROOT: /var/lib/dokku/var/lib/dokku
    restart: unless-stopped
    networks:
      - service-mesh

  control-plane:
    container_name: control-plane
    build:
      context: ..
      dockerfile: modules/kuma/Dockerfile
    environment:
      KUMA_MODE: standalone
    ports:
      - "5681:5681" # Admin REST API
      - "8080:8080" # Kuma GUI
      - "5678:5678" # Dataplane communication
    networks:
      - service-mesh

  gateway:
    container_name: gateway
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
    ports:
      - "8000:8000" # Proxy
      - "8001:8001" # Admin API
    networks:
      - service-mesh

  docker-in-docker:
    container_name: docker-in-docker
    image: docker:24.0.5-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - /var/lib/docker
    networks:
      - service-mesh

  service-a:
    build:
      context: ../apps/node-service-a
    container_name: service-a
    environment:
      KUMA_DPP: "service-a"
    depends_on:
      - control-plane
    networks:
      - service-mesh

  service-b:
    build:
      context: ../apps/node-service-b
    container_name: service-b
    environment:
      KUMA_DPP: "service-b"
    depends_on:
      - control-plane
      - service-a
    networks:
      - service-mesh

networks:
  service-mesh:
    driver: host
